### ISSUE TITLE
Can't find stop places with no valid version from UI

### ISSUE THREAD

**Issue by mhicauber** [entur/tiamat#12]
Due to versionValidity being set to CURRENT by default and no way to change this from UI, when searching for stop places with no valid current version no result is returned, even if pointInTime is null (pointInTime == null && version==ALL was the way to search for stop places until now)

**Comment by mhicauber** [comment]
see commit 19aafd8

**Comment by csolem** [comment]
It should still be possible to use the *allVersions* parameter to get all versions.
The difference is that if none of *allVersions*, *version*, *pointInTime* or *versionValidity* is given, the query will use default *versionValidity*:current.

**Comment by csolem** [comment]
Abzu and Tiamat (graphql) were both changed to use the *versionValidity* argument to fetch max version of stop places.
