### ISSUE TITLE
Async export with topographicPlaceExportMode=ALL produces duplicates in netex

### ISSUE THREAD

**Issue by mhicauber** [entur/tiamat#8]
Using async export with topographicPlaceExportMode=ALL, I get a netex file with : 
- All counties at the top of the file,
- Then all municipalities

But, when a municipality refers to a county as a parent topographic place, the county is included a second time in the netex file, just before the first municipality refering to it.

I'll try to fix it if I get some time.

**Comment by csolem** [comment]
It could be related to the usage of [ParentTreeTopographicPlaceFetchingIterator](https://github.com/entur/tiamat/blob/master/src/main/java/org/rutebanken/tiamat/exporter/async/ParentTreeTopographicPlaceFetchingIterator.java) in  [StreamingPublicationDelivery](https://github.com/entur/tiamat/blob/master/src/main/java/org/rutebanken/tiamat/exporter/StreamingPublicationDelivery.java#L243)

It should probably not use the parent fetching iterator for export mode ALL.

**Comment by csolem** [comment]
I managed to reproduce it using an integration test. Will try to submit a fix soon.
